Repository ucsb-cs156-s23/proj-happycows-s23-6pm-1, pull requests merged in 2023-06, with the labels that each got.

#37 pc - update workflow 33 to publish stryker report even if coverage is below 100%
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff

#31 Fix profit table overflow
  frontend/src/main/components/OurTable.js
Labels: s23-6pm-1

#32 Use cow health update strategies in frontend
  frontend/src/fixtures/healthUpdateStrategyListFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: s23-6pm-1, Merge Candidate-pending staff testing

#38 Show number of days and players on Commons Overview
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/main/utils/dateUtils.js
  frontend/src/stories/components/Commons/CommonsOverview.stories.mdx
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/components/Commons/ManageCows.test.js
  frontend/src/tests/pages/PlayPage.test.js
  frontend/src/tests/utils/dateUtils.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: s23-6pm-1, 10

#47 Redesign play page UI
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/components/Commons/Profits.js
  frontend/src/main/components/Commons/ProfitsTable.js
  frontend/src/tests/components/Commons/Profits.test.js
  frontend/src/tests/components/Commons/ProfitsTable.test.js
Labels: s23-6pm-1

#48 pc - update workflows
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/30-frontend-tests.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
  .github/workflows/52-storybook-main-branch.yml
  .github/workflows/54-storybook-pr.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
Labels: staff

#51 Remove redundant stories file
  frontend/src/stories/pages/Commons/CommonsCreatePage.stories.js
Labels: 5

#44 jz - Added feature that tracks total cows bought, sold, and died
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Commons/FarmStats.test.js
  frontend/src/tests/components/Commons/ManageCows.test.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: s23-6pm-1, 20, Merge Candidate-pending staff testing

#50 Adding Placeholder Instructor Report Button to Job Table
  frontend/src/fixtures/jobsFixtures.js
  frontend/src/main/components/Jobs/InstructorReportForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/stories/components/Jobs/InstructorReportForm.stories.mdx
  frontend/src/tests/components/Jobs/InstructorReportForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: s23-6pm-1

#46 Refactor UserCommons table to use a better table definition
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Profit.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommonsKey.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/SetCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/UserCommonsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/UserCommonsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/MilkTheCowsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/SetCowHealthJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: s23-6pm-1
